workflows:
  jasmina_android:
    name: JasminaAI Android
    environment:
      flutter: stable
    scripts:
      - name: Create Android platform
        script: flutter create --platforms=android .
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
